All Smartbugs tools' output converted to SARIF v2.1.0
smartbugs/smartbugs pull request #40
Opened 2021-05-20 13:19 UTC by dindonero

2021-05-21 18:06 UTC, ruimaranhao requested changes

2021-05-22 14:56 UTC, dindonero commented on README.md
> +              --v1-output           # outputs SmartBugs' version 1 json output
added option --output-version={v1, v2, all}

2021-05-22 15:01 UTC, dindonero commented on smartBugs.py
> +from src.output_parser.SarifHolder import SarifHolder
fixed

2021-05-24 14:39 UTC, ruimaranhao approved these changes
General note: do smaller PRs!

2021-07-29 09:42 UTC, jff approved these changes

2021-07-29 09:43 UTC, merged